# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.15.1
  hooks:
  # - id: check-github-actions
  - id: check-github-workflows
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.3  # Use the sha / tag you want to point at
  hooks:
  - id: clang-format
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
  - id: markdownlint-fix
